export enum IngredientsType {
    GET_INGREDIENTS = 'GET_INGREDIENTS',
    SET_INGREDIENTS = 'SET_INGREDIENTS',
    SELECT_INGREDIENT = 'SELECT_INGREDIENT',
    CHECK_IF_SANDWICH = 'CHECK_IF_SANDWICH'
  }
  